# Generated by Django 5.0.6 on 2024-09-30 11:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
        ("loans", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loans",
            name="backdate",
        ),
        migrations.RemoveField(
            model_name="loans",
            name="loansdate",
        ),
        migrations.AddField(
            model_name="loans",
            name="loan_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="loans",
            name="return_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loans",
            name="status",
            field=models.CharField(
                choices=[("ongoing", "En cours"), ("returned", "Retourné")],
                default="ongoing",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="loans",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="books.books"
            ),
        ),
    ]
