# Generated by Django 5.0.6 on 2024-09-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("pubdate", models.DateField()),
                ("isbn", models.CharField(max_length=13)),
                ("summary", models.CharField(default="")),
                ("gender", models.CharField(max_length=255)),
                ("availability", models.CharField(max_length=4)),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="book_covers/"),
                ),
            ],
        ),
    ]
